In [2]:
import os
import pandas as pd

In [3]:
group_price_df = pd.read_csv("group_price_df.csv")

k = group_price_df["종목코드"]
code = []
for i in k:
    if len(str(i)) < 6:
        a = (6 - len(str(i))) * '0' + str(i)
        code.append(a)
    else:
        code.append(str(i))



group_price_df = group_price_df.drop("Unnamed: 0", axis=1)
group_price_df["종목코드"] = code
group_price_df = group_price_df.set_index("종목코드")

In [7]:
for i in code:
    data = pd.read_csv(os.getcwd() + "\\재무\\%s_naverfinance.csv" %i, encoding = 'cp949')
    data = data.drop(["Unnamed: 0", "연간.5", "연간.6", "연간.7"], axis = 1)
    data.loc[34] = ["GP"] + group_price_df.loc[i].tolist()
    data.to_csv("재무revised\\%s.csv" %i, encoding = 'cp949')

In [18]:
a = pd.read_csv("재무revised\\000070.csv", encoding = 'cp949')

In [19]:
a = a.drop("Unnamed: 0", axis =1)

In [14]:
a = a.transpose()

In [21]:
a.columns = ["code_year", '']

,주요재무정보,연간,연간.1,연간.2,연간.3,연간.4
0,주요재무정보,2015/12 (IFRS연결),2016/12 (IFRS연결),2017/12 (IFRS연결),2018/12 (IFRS연결),2019/12 (IFRS연결)
1,매출액,21696.0,23115.0,23963.0,25635.0,24886.0
2,영업이익,1067.0,1410.0,988.0,1385.0,794.0
3,영업이익(발표기준),1067.0,1410.0,988.0,1385.0,794.0
4,세전계속사업이익,1049.0,1027.0,894.0,1293.0,810.0
5,당기순이익,780.0,651.0,672.0,1025.0,620.0
6,당기순이익(지배),465.0,226.0,377.0,700.0,309.0
7,당기순이익(비지배),315.0,425.0,295.0,325.0,312.0
8,자산총계,30714.0,31694.0,32760.0,33138.0,35895.0
9,부채총계,12751.0,13188.0,13362.0,13119.0,15600.0
10,자본총계,17964.0,18506.0,19398.0,20019.0,20295.0
11,자본총계(지배),13421.0,13526.0,13735.0,14116.0,14196.0
12,자본총계(비지배),4543.0,4980.0,5565.0,NaN,NaN
13,자본금,443.0,443.0,443.0,443.0,443.0
14,영업활동현금흐름,899.0,2171.0,-219.0,875.0,2189.0
15,투자활동현금흐름,-526.0,-680.0,-2422.0,-624.0,-3223.0
16,재무활동현금흐름,-852.0,-624.0,1258.0,-202.0,1621.0
17,CAPEX,960.0,1303.0,871.0,1583.0,1578.0
18,FCF,-62.0,867.0,-1090.0,-708.0,612.0
19,이자발생부채,8096.0,7833.0,8210.0,7786.0,10378.0
20,영업이익률,4.92,6.1,4.12,5.4,3.19
21,순이익률,3.6,2.82,2.8,4.0,2.49
22,ROE(%),3.5,1.68,2.76,5.03,2.18
23,ROA(%),2.66,2.09,2.08,3.11,1.8
24,부채비율,70.98,71.26,68.88,65.53,76.87
25,자본유보율,2868.04,2881.71,2928.91,3047.14,3077.36
26,EPS(원),5242.0,2550.0,4248.0,7890.0,3481.0
27,PER(배),30.33,46.87,28.72,9.95,19.25
28,BPS(원),173590.0,174957.0,177535.0,182460.0,183426.0
29,PBR(배),0.92,0.68,0.69,0.43,0.37
30,현금DPS(원),1500.0,2000.0,2000.0,2000.0,2000.0
31,현금배당수익률,0.94,1.67,1.64,2.55,2.99
32,현금배당성향(%),24.98,68.45,41.08,22.13,50.19
33,발행주식수(보통주),8564271.0,8564271.0,8564271.0,8564271.0,8564271.0
34,GP,2.0,0.0,0.0,0.0,0.0

In [93]:
a.transpose()

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
주요재무정보,주요재무정보,매출액,영업이익,영업이익(발표기준),세전계속사업이익,당기순이익,당기순이익(지배),당기순이익(비지배),자산총계,부채총계,...,자본유보율,EPS(원),PER(배),BPS(원),PBR(배),현금DPS(원),현금배당수익률,현금배당성향(%),발행주식수(보통주),70
연간,2015/12 (IFRS연결),21696.0,1067.0,1067.0,1049.0,780.0,465.0,315.0,30714.0,12751.0,...,2868.04,5242.0,30.33,173590.0,0.92,1500.0,0.94,24.98,8564271.0,2
연간.1,2016/12 (IFRS연결),23115.0,1410.0,1410.0,1027.0,651.0,226.0,425.0,31694.0,13188.0,...,2881.71,2550.0,46.87,174957.0,0.68,2000.0,1.67,68.45,8564271.0,0
연간.2,2017/12 (IFRS연결),23963.0,988.0,988.0,894.0,672.0,377.0,295.0,32760.0,13362.0,...,2928.91,4248.0,28.72,177535.0,0.69,2000.0,1.64,41.08,8564271.0,0
연간.3,2018/12 (IFRS연결),25635.0,1385.0,1385.0,1293.0,1025.0,700.0,325.0,33138.0,13119.0,...,3047.14,7890.0,9.95,182460.0,0.43,2000.0,2.55,22.13,8564271.0,0
연간.4,2019/12 (IFRS연결),24886.0,794.0,794.0,810.0,620.0,309.0,312.0,35895.0,15600.0,...,3077.36,3481.0,19.25,183426.0,0.37,2000.0,2.99,50.19,8564271.0,0

In [34]:
group_price_df = group_price_df.drop("15-16", axis = 1)

In [38]:
group_price_df.columns = ["2016/12", "2017/12", "2018/12", "2019/12"]

In [57]:
group_price_df.to_csv("aaaa.csv", encoding = 'cp949')

In [58]:
group_price_df

        2016/12  2017/12  2018/12  2019/12
종목코드
000070      0.0      0.0      0.0        0
000080      0.0      1.0      0.0        2
000100      0.0      0.0      1.0        0
000120      0.0      0.0      2.0        0
000150      1.0      1.0      0.0        0
...         ...      ...      ...      ...
282330      NaN      NaN      2.0        0
285130      NaN      NaN      0.0        2
294870      NaN      NaN      NaN        0
298040      NaN      NaN      NaN        0
316140      NaN      NaN      NaN        0

[200 rows x 4 columns]

In [71]:
kkk = []
for i in range(200):
    qwe = group_price_df.iloc[i].tolist()
    kkk += qwe

In [74]:
kkk

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 2.0,
 2.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 2.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 2.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 2.0,
 0.0,
 2.0,
 2.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 2.0,
 1.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 2.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 2.0,
 1.0,
 1.0,
 0.0,
 2.0,
 2.0,
 0.0,
 1.0,
 2.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 2.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 2.0,
 0.0,
 1.0,
 0.0,
 2.0,
 0.0,
 2.0,
 2.0,
 1.0,
 1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 2.0,
 2.0,
 0.0,
 2.0,
 0.0,
 1.0,
 1.0,
 2.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 2.0,
 2.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 2.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 2.0,
 1.0,
 0.0,
 1.0,
 2.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 2.0,
 0.0,
 1.0,
 0.0,
 2.0,
 2.0,
 1.0,
 0.0,
 nan,
 nan,
 2.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 2.0,
 0.0,
 2.0,
 2.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 2.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 2.0,
 0.0,
 2.0,
 0.0,
 2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 2.0,
 0.0,
 2.0,
 0.0,
 2.0,
 2.0,
 1.0,
 0.0,
 0.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 0.0,
 1.0,
 0.0,
 2.0,
 1.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 2.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 1.0,
 2.0,
 1.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 2.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 2.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 2.0,
 1.0,
 0.0,
 0.0,
 2.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 nan,
 2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 2.0,
 2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 nan,
 2.0,
 0.0,
 2.0,
 0.0,
 1.0,
 1.0,
 0.0,
 nan,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 0.0,
 0.0,
 nan,
 nan,
 0.0,
 1.0,
 nan,
 nan,
 2.0,
 0.0,
 nan,
 nan,
 0.0,
 2.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 0.0]

In [49]:
k = b["종목코드"]
code = []
for i in k:
    if len(str(i)) < 6:
        a = (6 - len(str(i))) * '0' + str(i)
        code.append(a)
    else:
        code.append(str(i))

In [50]:
code

['000070',
 '000080',
 '000100',
 '000120',
 '000150',
 '000210',
 '000240',
 '000270',
 '000640',
 '000660',
 '000670',
 '000720',
 '000810',
 '000880',
 '000990',
 '001040',
 '001060',
 '001120',
 '001230',
 '001430',
 '001450',
 '001520',
 '001680',
 '001740',
 '001800',
 '002240',
 '002270',
 '002350',
 '002380',
 '002790',
 '002960',
 '003000',
 '003240',
 '003410',
 '003490',
 '003520',
 '003550',
 '003620',
 '003850',
 '003920',
 '004000',
 '004020',
 '004170',
 '004370',
 '004490',
 '004800',
 '004990',
 '005180',
 '005250',
 '005300',
 '005380',
 '005440',
 '005490',
 '005610',
 '005830',
 '005850',
 '005930',
 '005940',
 '006120',
 '006260',
 '006280',
 '006360',
 '006390',
 '006400',
 '006650',
 '006800',
 '006840',
 '007070',
 '007310',
 '007570',
 '008060',
 '008560',
 '008770',
 '008930',
 '009150',
 '009240',
 '009420',
 '009540',
 '009830',
 '010060',
 '010120',
 '010130',
 '010140',
 '010620',
 '010780',
 '010950',
 '011070',
 '011170',
 '011210',
 '011780',
 '011790',
 '012330',
 '012450',
 '012630',
 '012750',
 '014680',
 '014820',
 '014830',
 '015760',
 '016360',
 '017670',
 '017800',
 '018250',
 '018260',
 '018880',
 '019680',
 '020000',
 '020150',
 '021240',
 '023530',
 '024110',
 '025540',
 '025860',
 '026960',
 '027410',
 '028050',
 '028260',
 '028670',
 '029780',
 '030000',
 '030200',
 '031430',
 '032640',
 '032830',
 '033780',
 '034020',
 '034220',
 '034730',
 '035250',
 '035420',
 '035720',
 '036460',
 '036570',
 '042660',
 '042670',
 '047040',
 '047050',
 '047810',
 '049770',
 '051600',
 '051900',
 '051910',
 '052690',
 '055550',
 '057050',
 '060980',
 '064350',
 '064960',
 '066570',
 '068270',
 '069260',
 '069620',
 '069960',
 '071050',
 '071840',
 '073240',
 '078930',
 '079160',
 '079430',
 '079550',
 '081660',
 '086280',
 '086790',
 '088350',
 '090430',
 '093050',
 '093370',
 '096760',
 '096770',
 '097950',
 '103140',
 '105560',
 '105630',
 '108670',
 '111770',
 '114090',
 '115390',
 '120110',
 '128940',
 '138930',
 '139480',
 '145990',
 '161390',
 '161890',
 '170900',
 '185750',
 '192400',
 '192820',
 '204320',
 '207940',
 '214320',
 '241560',
 '251270',
 '267250',
 '271560',
 '282330',
 '285130',
 '294870',
 '298040',
 '316140']

In [ ]:
for i in code:
    data = pd.read_csv(os.getcwd() + "\\재무\\%s_naverfinance.csv" %i, encoding = 'cp949')

In [59]:
aa = pd.read_csv("raw.csv", encoding='cp949')

In [60]:
k = aa["종목코드"]
code = []
for i in k:
    if len(str(i)) < 6:
        a = (6 - len(str(i))) * '0' + str(i)
        code.append(a)
    else:
        code.append(str(i))

In [61]:
aa["종목코드"] = code

In [62]:
aa["Group"] = 0

In [75]:
aa["Group"] = kkk

In [80]:
abc = aa.dropna()

In [83]:
abc.to_csv("raw_revised.csv", encoding = 'cp949')

In [84]:
abc

,Unnamed: 0,종목코드,해당년도,매출증감비율,영업이익증감비율,당기순이익증감비율,자산총계증감비율,부채비율,부채증감비율,PBR,PER,log(PBR증감비율),OPM,자본유보율,ROE,ROA,현금배당성향,Group
0,0,000070,2016/12,0.045475,0.010992,-0.004134,1.031907,71.26,1.034272,0.68,46.87,-0.302281,6.10,2881.71,1.68,2.09,68.45,0.0
1,1,000070,2017/12,0.026313,-0.013095,0.000652,1.033634,68.88,1.013194,0.69,28.72,0.014599,4.12,2928.91,2.76,2.08,41.08,0.0
2,2,000070,2018/12,0.050745,0.012049,0.010714,1.011538,65.53,0.981814,0.43,9.95,-0.472906,5.40,3047.14,5.03,3.11,22.13,0.0
3,3,000070,2019/12,-0.021700,-0.017122,-0.011734,1.083198,76.87,1.189115,0.37,19.25,-0.150282,3.19,3077.36,2.18,1.80,50.19,0.0
4,4,000080,2016/12,-0.005043,-0.002915,-0.004372,0.982835,163.26,0.987499,1.14,39.18,-0.075986,6.56,271.98,2.94,1.12,163.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783,783,282330,2019/12,0.093133,0.003885,-0.001532,1.465264,248.93,1.612863,4.70,19.35,-0.363460,3.31,3372.48,26.46,8.28,30.81,0.0
786,786,285130,2018/12,0.662611,0.028422,-0.003365,1.020079,168.87,1.037338,1.32,151.41,inf,3.34,1020.34,0.87,-0.85,87.64,0.0
787,787,285130,2019/12,0.029149,0.016950,0.010484,1.092731,196.60,1.153281,1.18,79.34,-0.112117,5.63,1003.20,1.51,0.25,56.68,2.0
791,791,294870,2019/12,0.307085,0.050383,0.039642,0.906691,97.58,0.721365,0.53,2.89,-0.833729,13.08,916.87,20.30,8.92,5.31,0.0
795,795,298040,2019/12,0.430737,0.021605,0.003794,1.165564,303.92,1.190877,0.27,18.91,-0.465363,3.45,1910.73,1.45,0.43,0.00,0.0

In [5]:
adjusted_group_price_df = pd.read_csv("C:/Users/eaststate/Desktop/스마/Project_Stock_Screener/adjusted_group_price_df.csv", encoding='cp949')

k = adjusted_group_price_df["종목코드"]
code = []
for i in k:
    if len(str(i)) < 6:
        a = (6 - len(str(i))) * '0' + str(i)
        code.append(a)
    else:
        code.append(str(i))



adjusted_group_price_df = adjusted_group_price_df.drop("Unnamed: 0", axis=1)
adjusted_group_price_df["종목코드"] = code
adjusted_group_price_df = adjusted_group_price_df.set_index("종목코드")
adjusted_group_price_df

        15-16  16-17  17-18  18-19  19-20
종목코드
000070    2.0    0.0    0.0    1.0      0
000080    1.0    0.0    1.0    1.0      2
000100    2.0    0.0    1.0    2.0      2
000120    1.0    1.0    0.0    2.0      2
000150    0.0    1.0    1.0    1.0      0
...       ...    ...    ...    ...    ...
282330    NaN    NaN    NaN    2.0      1
285130    NaN    NaN    NaN    0.0      2
294870    NaN    NaN    NaN    NaN      0
298040    NaN    NaN    NaN    NaN      0
316140    NaN    NaN    NaN    NaN      0

[200 rows x 5 columns]

In [ ]:
aa = pd.read_csv("raw.csv", encoding='cp949')
k = aa["종목코드"]
code = []
for i in k:
    if len(str(i)) < 6:
        a = (6 - len(str(i))) * '0' + str(i)
        code.append(a)
    else:
        code.append(str(i))
aa["종목코드"] = code
aa["Group"] = 0